#!/bin/sh
set -e

TARGET=10.0.100.3
USER=root
SSH_ARGS="-o ConnectTimeout=5 -o StrictHostKeyChecking=no"
API_PORT=8081

echo "Building..."
GOOS=linux GOARCH=arm go build -o frc-radio-api

echo "\nDeploying to $TARGET..."
ssh $SSH_ARGS $USER@$TARGET "/etc/init.d/frc-radio-api stop"
scp -O $SSH_ARGS frc-radio-api $USER@$TARGET:/usr/bin/
scp -O $SSH_ARGS frc-radio-api.init $USER@$TARGET:/etc/init.d/frc-radio-api
ssh $SSH_ARGS $USER@$TARGET "chmod +x /usr/bin/frc-radio-api /etc/init.d/frc-radio-api && /etc/init.d/frc-radio-api start"

echo "\nChecking health..."
sleep 1
(curl -s --fail "http://$TARGET:$API_PORT/health" | grep OK) || (echo "Health check failed." && exit 1)

echo "\nDeployed successfully."
