// Code generated by "stringer -type=RadioType"; DO NOT EDIT.

package radio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeLinksys-1]
	_ = x[TypeVividHosting-2]
}

const _RadioType_name = "TypeUnknownTypeLinksysTypeVividHosting"

var _RadioType_index = [...]uint8{0, 11, 22, 38}

func (i RadioType) String() string {
	if i < 0 || i >= RadioType(len(_RadioType_index)-1) {
		return "RadioType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RadioType_name[_RadioType_index[i]:_RadioType_index[i+1]]
}
