// Code generated by "stringer -type=radioType"; DO NOT EDIT.

package radio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[typeUnknown-0]
	_ = x[typeLinksys-1]
	_ = x[typeVividHosting-2]
}

const _radioType_name = "typeUnknowntypeLinksystypeVividHosting"

var _radioType_index = [...]uint8{0, 11, 22, 38}

func (i radioType) String() string {
	if i < 0 || i >= radioType(len(_radioType_index)-1) {
		return "radioType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _radioType_name[_radioType_index[i]:_radioType_index[i+1]]
}
